### ISSUE TITLE
Kubernetes integration: Duplicate logs?

### ISSUE THREAD

**Issue by sajal** [logdna/logdna-agent#19] opened 2017-04-12 09:46 UTC
I am trying out logdna and the kubernetes integration on a 5 node coreos cluster (2 master 3 workers).

Cluster is setup mostly as per [instructions from coreos](https://coreos.com/kubernetes/docs/latest/getting-started.html), logdna DS is setup as per instructions in readme.

I see for each log line emitted by by a pod, logdna shows me 2 entries. One with hostname=podname and another with hostname=<hostname of node> . This seams to happen for each entry from each pod.

Screenshot: https://db.sajalkayan.com/logdna.png

Does this mean I am consuming 2x of the storage I ought to? Is there something I can tune to not make it happen? Or is this just a UI thing and its not actually consuming 2x storage.

Ideally the agent should emit a single entry, and add fields for node hostname, podname and other kubernetes fields if possible.

**Comment by leeliu** [comment] 2017-04-12 10:04
Hey Sajal,

That's weird. I haven't seen a /var/log/pods/ before. Usually centralized logs only goto /var/log/containers. Is this something that coreos does? I can't seem to find any information on this and we don't have this on our cluster.

There are 2 ways around this:
1) You can modify the ds yaml and change `/var/log` to `/var/log/containers` and redeploy, that'll ignore the /var/log/pods dir, though you'll also lose node/kubelet logs.
2) On our web app, click Gear icon > Ingestion > Under keywords, you can type something like `_file:/var/log/pods/` and it'll filter out everything from just that dir.

Either case, we'll try to dig a bit deeper on `/var/log/pods` and see if we can confirm that it's a simple duplicate of all logs....seems rather redundant on k8s' part.

**Comment by sajal** [comment] 2017-04-12 11:53
seems `/var/log/containers/*` is symlink to `/var/log/pods/*`

Mounting just `/var/log/containers` produces no log output, i guess because of broken symlink.
Mounting just `/var/log/pods` produces output with node name as hostname without a pod identifier.

So I will revert to the normal yaml and use the ingestion filter you suggested.

Will also try to dig where my symlink setup came from.

```
core@coreos-6 ~ $ ls -lh /var/log/pods/
total 40K
drwxr-xr-x. 2 root root 4.0K Apr 12 11:37 10c55096-1f74-11e7-bb03-1a1fff709857
drwxr-xr-x. 2 root root 4.0K Apr 12 11:37 10c57edb-1f74-11e7-bb03-1a1fff709857
drwxr-xr-x. 2 root root 4.0K Apr 12 11:36 10cfd0d4-1f74-11e7-bb03-1a1fff709857
drwxr-xr-x. 2 root root 4.0K Apr 12 11:34 222beeaabe95be458a5ba53ca8996ca8
drwxr-xr-x. 2 root root 4.0K Apr 12 11:36 748ecd0d3770fd3f942ebc95e4874cb0
core@coreos-6 ~ $ ls -lh /var/log/containers/
total 40K
lrwxrwxrwx. 1 root root 60 Apr 12 11:34 haproxy-10.130.48.188_kube-system_haproxy-03a5ff3dc23ccd1bd5fdc7ae3ec6aa1ce0d093278a432264ae6514013b26d203.log -> /var/log/pods/222beeaabe95be458a5ba53ca8996ca8/haproxy_0.log
lrwxrwxrwx. 1 root root 63 Apr 12 11:36 kube-proxy-10.130.48.188_kube-system_kube-proxy-b107f5ba8e7f5e227e84ca637152d51629284d22823e525b9c5492bc2cff166e.log -> /var/log/pods/748ecd0d3770fd3f942ebc95e4874cb0/kube-proxy_0.log
lrwxrwxrwx. 1 root root 69 Apr 12 11:37 logdna-agent-zsl41_default_logdna-agent-49bb7669e420381f438af0cf4ace1f6d9d89ea9fa4953106fa559f2acd93fd04.log -> /var/log/pods/10c57edb-1f74-11e7-bb03-1a1fff709857/logdna-agent_0.log
lrwxrwxrwx. 1 root root 70 Apr 12 11:36 nginx-mfcw6_default_nginx-ingress-10ad8d8223286d47ed6c64a003377672b8b93d2a658a9a46ae672b65055ac47e.log -> /var/log/pods/10cfd0d4-1f74-11e7-bb03-1a1fff709857/nginx-ingress_0.log
lrwxrwxrwx. 1 root root 60 Apr 12 11:37 osd-82m1n_rook_osd-3b1d3ccca12bcb3a8c5a92a2ae8e78621a2630a4f439fa35dc04b4108a7a857e.log -> /var/log/pods/10c55096-1f74-11e7-bb03-1a1fff709857/osd_0.log
core@coreos-6 ~ $ 
```

**Comment by leeliu** [comment] 2017-04-12 12:24
Thanks for the thorough output! Greatly helps. What version of Kubernetes? And CoreOS? I'm going to try to repro what you have.

**Comment by sajal** [comment] 2017-04-12 13:55
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+coreos.0", GitCommit:"9212f77ed8c169a0afa02e58dce87913c6387b3e", GitTreeState:"clean", BuildDate:"2017-04-04T00:32:53Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
core@coreos-6 ~ $ cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.7.0
VERSION_ID=1298.7.0
BUILD_ID=2017-03-31-0215
PRETTY_NAME="Container Linux by CoreOS 1298.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
core@coreos-6 ~ $ 
```

I can't find any reference to `/var/log/pods` in my scripts, but the coreos way [runs the kubelet itself using rkt](https://coreos.com/kubernetes/docs/latest/deploy-workers.html#create-the-kubelet-unit). Everything else runs on docker.

**Comment by leeliu** [comment] 2017-04-13 01:28
Got it. You guys are using 1.6.x which came out about 2 weeks ago. This describes it in more detail: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubelet-cri-logging.md though your current logging format still does look like the old one but the paths are new. We'll update our stuff to handle this natively on our end. Shouldn't require any changes on your side.

**Comment by leeliu** [comment] 2017-06-28 23:22
Okay we've done some testing and we now exclude all /var/log/pods/*

**Closed by leeliu** 2017-06-28 23:22 UTC

**Comment by uvais-kr** [comment] 2022-08-17 09:50
Hi all, getting duplicates pods logs of each instance in Rancher of Kubernetes cluster deployment.

snap: -
![image](https://user-images.githubusercontent.com/103558870/185089419-8194973c-b562-4a6c-b5c7-ce5780a683aa.png)

Deep Insight will be appreciated!
